# Specifying the joint we want to be set to calibrated = true
head_swivel_fake_calib:
  type: sr_ronex_controllers/FakeCalibrationController
  joint: head_swivel

# Settings for a simple joint position controller
head_swivel_controller:
  type: sr_ronex_examples/SrRoNeXSimpleController
  joint: head_swivel
